export interface User {
  id: string;
  email: string;
  username: string;
  password?: string;
  firstName: string;
  lastName: string;
  isActive: boolean;
  isEmailVerified: boolean;
  emailVerificationToken?: string;
  passwordResetToken?: string;
  passwordResetExpires?: Date;
  lastLoginAt?: Date;
  loginAttempts: number;
  lockedUntil?: Date;
  ssoProvider?: string;
  ssoId?: string;
  createdAt: Date;
  updatedAt: Date;
  userRoles?: UserRoleInterface[];
}

export interface UserRoleInterface {
  id: string;
  userId: string;
  roleId: string;
  programId?: string;
  assignedAt: Date;
  assignedBy?: string;
  isActive: boolean;
  role?: Role;
}

export interface Role {
  id: string;
  name: string;
  description?: string;
  isActive: boolean;
  isPredefined: boolean;
  category?: string;
  createdAt: Date;
  updatedAt: Date;
  createdBy?: string;
  rolePermissions?: RolePermission[];
}

export interface Permission {
  id: string;
  name: string;
  resource: string;
  action: string;
  scope: string;
  conditions?: any;
  description?: string;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface RolePermission {
  id: string;
  roleId: string;
  permissionId: string;
  grantedAt: Date;
  grantedBy?: string;
  permission?: Permission;
}

// Import and re-export UserRole enum for controllers
import { UserRole } from '@libs/common';
export { UserRole };

export class UserEntity implements User {
  constructor(
    public id: string,
    public email: string,
    public username: string,
    public password: string | undefined,
    public firstName: string,
    public lastName: string,
    public isActive: boolean = true,
    public isEmailVerified: boolean = false,
    public emailVerificationToken: string | undefined = undefined,
    public passwordResetToken: string | undefined = undefined,
    public passwordResetExpires: Date | undefined = undefined,
    public lastLoginAt: Date | undefined = undefined,
    public loginAttempts: number = 0,
    public lockedUntil: Date | undefined = undefined,
    public ssoProvider: string | undefined = undefined,
    public ssoId: string | undefined = undefined,
    public createdAt: Date = new Date(),
    public updatedAt: Date = new Date(),
    public userRoles?: UserRoleInterface[],
  ) {}

  static create(
    email: string,
    username: string,
    password: string | undefined,
    firstName: string,
    lastName: string,
  ): UserEntity {
    return new UserEntity(
      '', // ID will be generated by the database
      email,
      username,
      password,
      firstName,
      lastName,
    );
  }

  updateProfile(firstName: string, lastName: string): void {
    this.firstName = firstName;
    this.lastName = lastName;
    this.updatedAt = new Date();
  }

  deactivate(): void {
    this.isActive = false;
    this.updatedAt = new Date();
  }

  activate(): void {
    this.isActive = true;
    this.updatedAt = new Date();
  }

  hasRole(roleName: string): boolean {
    return this.userRoles?.some(userRole => userRole.role?.name === roleName) || false;
  }

  hasPermission(resource: string, action: string, scope: string = 'global'): boolean {
    return this.userRoles?.some(userRole => 
      userRole.role?.rolePermissions?.some(rolePermission => 
        rolePermission.permission?.resource === resource &&
        rolePermission.permission?.action === action &&
        rolePermission.permission?.scope === scope &&
        rolePermission.permission?.isActive
      )
    ) || false;
  }

  getAllPermissions(): Permission[] {
    const permissions: Permission[] = [];
    this.userRoles?.forEach(userRole => {
      userRole.role?.rolePermissions?.forEach(rolePermission => {
        if (rolePermission.permission && rolePermission.permission.isActive) {
          permissions.push(rolePermission.permission);
        }
      });
    });
    return permissions;
  }

  isAccountLocked(): boolean {
    return this.lockedUntil ? this.lockedUntil > new Date() : false;
  }

  incrementLoginAttempts(): void {
    this.loginAttempts += 1;
    this.updatedAt = new Date();
    
    // Lock account after 5 failed attempts for 15 minutes
    if (this.loginAttempts >= 5) {
      this.lockedUntil = new Date(Date.now() + 15 * 60 * 1000);
    }
  }

  resetLoginAttempts(): void {
    this.loginAttempts = 0;
    this.lockedUntil = undefined;
    this.lastLoginAt = new Date();
    this.updatedAt = new Date();
  }

  getFullName(): string {
    return `${this.firstName} ${this.lastName}`;
  }
}
