export enum InstanceStatus {
  SCHEDULED = 'SCHEDULED',
  CONFIRMED = 'CONFIRMED',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED',
  NO_SHOW = 'NO_SHOW',
  MODIFIED = 'MODIFIED',
  SKIPPED = 'SKIPPED',
  PENDING = 'PENDING'
}
