export enum LimitType {
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
  CONCURRENT = 'CONCURRENT',
  TOTAL = 'TOTAL',
  DURATION = 'DURATION',
  ADVANCE_BOOKING = 'ADVANCE_BOOKING',
  CANCELLATION_WINDOW = 'CANCELLATION_WINDOW',
  MODIFICATION_WINDOW = 'MODIFICATION_WINDOW',
  RECURRING_INSTANCES = 'RECURRING_INSTANCES',
  WAITING_LIST_SIZE = 'WAITING_LIST_SIZE',
  PENALTY_THRESHOLD = 'PENALTY_THRESHOLD',
  RESOURCE_USAGE = 'RESOURCE_USAGE',
  TIME_SLOT_DURATION = 'TIME_SLOT_DURATION',
  OVERLAP_PREVENTION = 'OVERLAP_PREVENTION'
}
