export enum PenaltyEventType {
  NO_SHOW = 'NO_SHOW',
  LATE_CANCELLATION = 'LATE_CANCELLATION',
  RESOURCE_DAMAGE = 'RESOURCE_DAMAGE',
  POLICY_VIOLATION = 'POLICY_VIOLATION',
  EXCESSIVE_MODIFICATIONS = 'EXCESSIVE_MODIFICATIONS',
  UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS',
  MISUSE_OF_RESOURCE = 'MISUSE_OF_RESOURCE',
  REPEATED_VIOLATIONS = 'REPEATED_VIOLATIONS',
  FALSE_INFORMATION = 'FALSE_INFORMATION',
  SYSTEM_ABUSE = 'SYSTEM_ABUSE'
}
