export enum ReassignmentReason {
  MAINTENANCE = 'MAINTENANCE',
  TECHNICAL_ISSUES = 'TECHNICAL_ISSUES',
  CAPACITY_CHANGE = 'CAPACITY_CHANGE',
  FACILITY_UNAVAILABLE = 'FACILITY_UNAVAILABLE',
  EMERGENCY = 'EMERGENCY',
  ADMINISTRATIVE = 'ADMINISTRATIVE',
  OTHER = 'OTHER',
  RESOURCE_UNAVAILABLE = 'RESOURCE_UNAVAILABLE',
  CONFLICT = 'CONFLICT',
  UPGRADE = 'UPGRADE',
  USER_REQUEST = 'USER_REQUEST',
  OPTIMIZATION = 'OPTIMIZATION',
  TECHNICAL_ISSUE = 'TECHNICAL_ISSUE',
  CAPACITY_EXCEEDED = 'CAPACITY_EXCEEDED',
  POLICY_VIOLATION = 'POLICY_VIOLATION',
  SCHEDULE_CHANGE = 'SCHEDULE_CHANGE',
  RESOURCE_DAMAGE = 'RESOURCE_DAMAGE'
}
