export enum RestrictionLevel {
  NONE = 'NONE',
  LIGHT = 'LIGHT',
  MODERATE = 'MODERATE',
  SEVERE = 'SEVERE',
  COMPLETE = 'COMPLETE',
  CONDITIONAL = 'CONDITIONAL',
  TEMPORARY = 'TEMPORARY',
  PERMANENT = 'PERMANENT',
  ESCALATING = 'ESCALATING',
  CUSTOM = 'CUSTOM',
  REVIEW_REQUIRED = 'REVIEW_REQUIRED',
  APPEAL_PENDING = 'APPEAL_PENDING',
  GRACE_PERIOD = 'GRACE_PERIOD',
  PROBATIONARY = 'PROBATIONARY'
}
