export enum TimeWindow {
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
  QUARTERLY = 'QUARTERLY',
  YEARLY = 'YEARLY',
  CUSTOM = 'CUSTOM',
  ROLLING_7_DAYS = 'ROLLING_7_DAYS',
  ROLLING_30_DAYS = 'ROLLING_30_DAYS',
  ROLLING_90_DAYS = 'ROLLING_90_DAYS',
  ACADEMIC_SEMESTER = 'ACADEMIC_SEMESTER',
  ACADEMIC_YEAR = 'ACADEMIC_YEAR',
  BUSINESS_HOURS = 'BUSINESS_HOURS',
  EXTENDED_HOURS = 'EXTENDED_HOURS',
  WEEKEND_ONLY = 'WEEKEND_ONLY',
  WEEKDAY_ONLY = 'WEEKDAY_ONLY'
}
