export enum NotificationEventType {
  RESERVATION_SUBMITTED = 'RESERVATION_SUBMITTED',
  RESERVATION_APPROVED = 'RESERVATION_APPROVED',
  RESERVATION_REJECTED = 'RESERVATION_REJECTED',
  RESERVATION_CANCELLED = 'RESERVATION_CANCELLED',
  APPROVAL_REMINDER = 'APPROVAL_REMINDER',
  RESERVATION_REMINDER = 'RESERVATION_REMINDER',
  AVAILABILITY_CONFIRMATION = 'AVAILABILITY_CONFIRMATION',
  AVAILABILITY_UNAVAILABLE = 'AVAILABILITY_UNAVAILABLE',
  ALTERNATIVE_SUGGESTIONS = 'ALTERNATIVE_SUGGESTIONS'
}
