name: SSH Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Entorno de despliegue'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      service:
        description: 'Servicio a desplegar (o "all" para todos)'
        required: true
        default: 'all'
        type: string
      tag:
        description: 'Tag de la imagen a desplegar'
        required: false
        default: 'latest'
        type: string
  repository_dispatch:
    types: [image-updated]

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ${{ github.repository_owner }}/bookly
  SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  prepare:
    name: Preparar variables
    runs-on: ubuntu-latest
    outputs:
      service: ${{ steps.vars.outputs.service }}
      tag: ${{ steps.vars.outputs.tag }}
      environment: ${{ steps.vars.outputs.environment }}
      trigger: ${{ steps.vars.outputs.trigger }}
    steps:
      - name: Determinar variables según trigger
        id: vars
        run: |
          if [ "${{ github.event_name }}" = "repository_dispatch" ]; then
            echo "trigger=auto" >> $GITHUB_OUTPUT
            echo "tag=${{ github.event.client_payload.tag }}" >> $GITHUB_OUTPUT
            echo "service=all" >> $GITHUB_OUTPUT
            echo "environment=staging" >> $GITHUB_OUTPUT
            echo "🤖 Despliegue automático detectado"
          else
            echo "trigger=manual" >> $GITHUB_OUTPUT
            echo "tag=${{ github.event.inputs.tag || 'latest' }}" >> $GITHUB_OUTPUT
            echo "service=${{ github.event.inputs.service || 'all' }}" >> $GITHUB_OUTPUT
            echo "environment=${{ github.event.inputs.environment || 'staging' }}" >> $GITHUB_OUTPUT
            echo "👤 Despliegue manual detectado"
          fi

  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest
    needs: prepare
    environment: ${{ needs.prepare.outputs.environment }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Validar secrets requeridos
        run: |
          if [ -z "${{ secrets.SSH_USERNAME }}" ]; then
            echo "❌ Error: SSH_USERNAME secret no está configurado"
            exit 1
          fi
          if [ -z "${{ secrets.SSH_HOST }}" ]; then
            echo "❌ Error: SSH_HOST secret no está configurado"
            exit 1
          fi
          if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
            echo "❌ Error: SSH_PRIVATE_KEY secret no está configurado"
            exit 1
          fi
          echo "✅ Todos los secrets están configurados"

      - name: Configurar SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts 2>/dev/null || true

      - name: Probar conexión SSH
        run: |
          echo "🔗 Probando conexión SSH a ${{ secrets.SSH_HOST }}..."
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no -o ConnectTimeout=30 \
            ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} \
            "echo '✅ Conexión SSH exitosa desde GitHub Actions'"

      - name: Login a GHCR en servidor remoto
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} \
            "echo '${{ secrets.GHCR_TOKEN }}' | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin"

      - name: Ejecutar despliegue desde GHCR
        env:
          DEPLOY_SERVICE: ${{ needs.prepare.outputs.service }}
          DEPLOY_TAG: ${{ needs.prepare.outputs.tag }}
          DEPLOY_ENV: ${{ needs.prepare.outputs.environment }}
        run: |
          echo "🚀 Desplegando servicio: $DEPLOY_SERVICE"
          echo "📍 Entorno: $DEPLOY_ENV"
          echo "🏷️ Tag: $DEPLOY_TAG"
          
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << EOF
          
          set -e
          
          # Variables del despliegue
          SERVICE="$DEPLOY_SERVICE"
          TAG="$DEPLOY_TAG"
          ENVIRONMENT="$DEPLOY_ENV"
          REGISTRY="${{ env.REGISTRY }}"
          IMAGE_PREFIX="${{ env.IMAGE_PREFIX }}"
          DEPLOY_DIR="/opt/bookly"
          
          SERVICES_LIST="auth availability gateway reports resources stockpile web"
          
          echo "📂 Directorio de despliegue: \$DEPLOY_DIR"
          cd \$DEPLOY_DIR || { echo "❌ No existe el directorio \$DEPLOY_DIR"; exit 1; }
          
          # Función para pull y deploy de un servicio
          deploy_service() {
            local svc=\$1
            local image="\${REGISTRY}/\${IMAGE_PREFIX}-\${svc}:\${TAG}"
            
            echo "📥 Pulling imagen: \$image"
            docker pull \$image || { echo "⚠️ No se pudo obtener \$image"; return 1; }
            
            echo "🔄 Actualizando servicio: \$svc"
            docker-compose -f docker-compose.\$ENVIRONMENT.yml up -d --no-deps \$svc
          }
          
          # Desplegar servicios
          if [ "\$SERVICE" = "all" ]; then
            echo "🔄 Desplegando todos los servicios..."
            for svc in \$SERVICES_LIST; do
              deploy_service \$svc || echo "⚠️ Falló \$svc, continuando..."
            done
            docker-compose -f docker-compose.\$ENVIRONMENT.yml up -d --remove-orphans
          else
            deploy_service \$SERVICE
          fi
          
          # Limpiar imágenes antiguas
          echo "🧹 Limpiando imágenes no utilizadas..."
          docker image prune -f
          
          # Verificar estado
          echo "📊 Estado de los contenedores:"
          docker-compose -f docker-compose.\$ENVIRONMENT.yml ps
          
          echo "✅ Despliegue completado exitosamente"
          
          EOF

      - name: Limpiar credenciales SSH
        if: always()
        run: |
          rm -f ~/.ssh/deploy_key
          echo "🧹 Credenciales SSH limpiadas"

      - name: Resumen del despliegue
        run: |
          echo "## 📋 Resumen del Despliegue desde GHCR" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Parámetro | Valor |" >> $GITHUB_STEP_SUMMARY
          echo "|-----------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| **Trigger** | ${{ needs.prepare.outputs.trigger }} |" >> $GITHUB_STEP_SUMMARY
          echo "| **Entorno** | ${{ needs.prepare.outputs.environment }} |" >> $GITHUB_STEP_SUMMARY
          echo "| **Servicio** | ${{ needs.prepare.outputs.service }} |" >> $GITHUB_STEP_SUMMARY
          echo "| **Tag** | ${{ needs.prepare.outputs.tag }} |" >> $GITHUB_STEP_SUMMARY
          echo "| **Registry** | \`${{ env.REGISTRY }}\` |" >> $GITHUB_STEP_SUMMARY
          echo "| **Host** | ${{ secrets.SSH_HOST }} |" >> $GITHUB_STEP_SUMMARY
          echo "| **Ejecutado por** | ${{ github.actor }} |" >> $GITHUB_STEP_SUMMARY
          echo "| **Fecha** | $(date -u '+%Y-%m-%d %H:%M:%S UTC') |" >> $GITHUB_STEP_SUMMARY
