/**
 * HITO 6 - RF-06: MaintenanceType Entity
 * Dynamic maintenance types with default system types
 */
export class MaintenanceTypeEntity {
  constructor(
    public readonly id: string,
    public readonly name: string,
    public readonly description: string | null,
    public readonly color: string | null,
    public readonly priority: number,
    public readonly isDefault: boolean,
    public readonly isActive: boolean,
    public readonly createdAt: Date,
    public readonly updatedAt: Date,
  ) {}

  /**
   * Creates a new maintenance type entity
   */
  static create(
    name: string,
    description?: string,
    color?: string,
    priority: number = 0,
    isDefault: boolean = false,
  ): MaintenanceTypeEntity {
    const now = new Date();
    
    return new MaintenanceTypeEntity(
      '', // ID will be generated by repository
      name.toUpperCase(),
      description || null,
      color || null,
      priority,
      isDefault,
      true,
      now,
      now,
    );
  }

  /**
   * Updates maintenance type information
   */
  update(
    name?: string,
    description?: string,
    color?: string,
    priority?: number,
  ): MaintenanceTypeEntity {
    // Default types cannot change their name
    const updatedName = this.isDefault ? this.name : (name?.toUpperCase() || this.name);
    
    return new MaintenanceTypeEntity(
      this.id,
      updatedName,
      description !== undefined ? description : this.description,
      color !== undefined ? color : this.color,
      priority !== undefined ? priority : this.priority,
      this.isDefault,
      this.isActive,
      this.createdAt,
      new Date(),
    );
  }

  /**
   * Deactivates the maintenance type (only if not default)
   */
  deactivate(): MaintenanceTypeEntity {
    if (this.isDefault) {
      throw new Error('Cannot deactivate default maintenance types');
    }

    return new MaintenanceTypeEntity(
      this.id,
      this.name,
      this.description,
      this.color,
      this.priority,
      this.isDefault,
      false,
      this.createdAt,
      new Date(),
    );
  }

  /**
   * Validates maintenance type name
   */
  static isValidName(name: string): boolean {
    return name.trim().length >= 3 && name.trim().length <= 50;
  }

  /**
   * Gets default maintenance types that must exist in the system
   */
  static getDefaultTypes(): Partial<MaintenanceTypeEntity>[] {
    return [
      {
        name: 'PREVENTIVO',
        description: 'Mantenimiento preventivo programado',
        color: '#4CAF50',
        priority: 1,
        isDefault: true,
      },
      {
        name: 'CORRECTIVO',
        description: 'Mantenimiento correctivo por fallas',
        color: '#FF9800',
        priority: 2,
        isDefault: true,
      },
      {
        name: 'EMERGENCIA',
        description: 'Mantenimiento de emergencia urgente',
        color: '#F44336',
        priority: 3,
        isDefault: true,
      },
    ];
  }

  /**
   * Checks if this is a default maintenance type
   */
  isDefaultType(): boolean {
    const defaultNames = ['PREVENTIVO', 'CORRECTIVO', 'EMERGENCIA'];
    return defaultNames.includes(this.name);
  }
}
