/**
 * HITO 6 - RF-02: Program Entity
 * Academic program for resource classification and management
 */
export class ProgramEntity {
  constructor(
    public readonly id: string,
    public readonly name: string,
    public readonly code: string,
    public readonly description: string | null,
    public readonly facultyName: string,
    public readonly isActive: boolean,
    public readonly createdAt: Date,
    public readonly updatedAt: Date,
  ) {}

  /**
   * Creates a new program entity
   */
  static create(
    name: string,
    code: string,
    facultyName: string,
    description?: string,
  ): ProgramEntity {
    const now = new Date();
    
    return new ProgramEntity(
      '', // ID will be generated by repository
      name,
      code,
      description || null,
      facultyName,
      true,
      now,
      now,
    );
  }

  /**
   * Updates program information
   */
  update(
    name?: string,
    description?: string,
    facultyName?: string,
  ): ProgramEntity {
    return new ProgramEntity(
      this.id,
      name || this.name,
      this.code, // Code cannot be changed
      description !== undefined ? description : this.description,
      facultyName || this.facultyName,
      this.isActive,
      this.createdAt,
      new Date(),
    );
  }

  /**
   * Deactivates the program
   */
  deactivate(): ProgramEntity {
    return new ProgramEntity(
      this.id,
      this.name,
      this.code,
      this.description,
      this.facultyName,
      false,
      this.createdAt,
      new Date(),
    );
  }

  /**
   * Validates program code format
   */
  static isValidCode(code: string): boolean {
    // Code should be uppercase, 3-10 characters, alphanumeric with hyphens
    const codeRegex = /^[A-Z0-9-]{3,10}$/;
    return codeRegex.test(code);
  }

  /**
   * Validates program name
   */
  static isValidName(name: string): boolean {
    return name.trim().length >= 3 && name.trim().length <= 100;
  }
}
