/**
 * HITO 6 - RF-02: ResourceResponsible Entity
 * Manages resource responsibility assignments
 */
export class ResourceResponsibleEntity {
  constructor(
    public readonly id: string,
    public readonly resourceId: string,
    public readonly userId: string,
    public readonly assignedBy: string,
    public readonly assignedAt: Date,
    public readonly isActive: boolean,
  ) {}

  /**
   * Creates a new resource responsibility assignment
   */
  static create(
    resourceId: string,
    userId: string,
    assignedBy: string,
  ): ResourceResponsibleEntity {
    return new ResourceResponsibleEntity(
      '', // ID will be generated by repository
      resourceId,
      userId,
      assignedBy,
      new Date(),
      true,
    );
  }

  /**
   * Deactivates the responsibility assignment
   */
  deactivate(): ResourceResponsibleEntity {
    return new ResourceResponsibleEntity(
      this.id,
      this.resourceId,
      this.userId,
      this.assignedBy,
      this.assignedAt,
      false,
    );
  }

  /**
   * Validates the assignment
   */
  static isValid(resourceId: string, userId: string, assignedBy: string): boolean {
    return (
      resourceId.trim().length > 0 &&
      userId.trim().length > 0 &&
      assignedBy.trim().length > 0 &&
      userId !== assignedBy // Cannot assign responsibility to oneself
    );
  }
}
