/**
 * HITO 6 - RF-04: ResourceImport Entity
 * Tracks CSV import operations and their results
 */
import { ImportStatus } from '@apps/resources-service/utils/import-status.enum';

export interface ImportError {
  row: number;
  field: string;
  value: any;
  message: string;
}

export interface ImportSummary {
  totalRows: number;
  successfulRows: number;
  failedRows: number;
  errors: ImportError[];
  warnings: string[];
  duration: number; // milliseconds
}

export class ResourceImportEntity {
  constructor(
    public readonly id: string,
    public readonly filename: string,
    public readonly originalFilename: string,
    public readonly totalRows: number,
    public readonly successfulRows: number,
    public readonly failedRows: number,
    public readonly status: ImportStatus,
    public readonly errors: ImportError[] | null,
    public readonly summary: ImportSummary | null,
    public readonly importedBy: string,
    public readonly importedAt: Date,
    public readonly completedAt: Date | null,
  ) {}

  /**
   * Creates a new resource import entity
   */
  static create(
    filename: string,
    originalFilename: string,
    totalRows: number,
    importedBy: string,
  ): ResourceImportEntity {
    return new ResourceImportEntity(
      '', // ID will be generated by repository
      filename,
      originalFilename,
      totalRows,
      0, // successfulRows - will be updated during processing
      0, // failedRows - will be updated during processing
      ImportStatus.PROCESSING,
      null, // errors - will be populated during processing
      null, // summary - will be generated when completed
      importedBy,
      new Date(),
      null, // completedAt - will be set when completed
    );
  }

  /**
   * Updates import progress
   */
  updateProgress(
    successfulRows: number,
    failedRows: number,
    errors?: ImportError[],
  ): ResourceImportEntity {
    return new ResourceImportEntity(
      this.id,
      this.filename,
      this.originalFilename,
      this.totalRows,
      successfulRows,
      failedRows,
      this.status,
      errors || this.errors,
      this.summary,
      this.importedBy,
      this.importedAt,
      this.completedAt,
    );
  }

  /**
   * Completes the import with final results
   */
  complete(successfulRows: number, failedRows: number, errors: any[], p0: { totalProcessed: number; successRate: string; processingTime: number; }, summary: ImportSummary): ResourceImportEntity {
    return new ResourceImportEntity(
      this.id,
      this.filename,
      this.originalFilename,
      this.totalRows,
      summary.successfulRows,
      summary.failedRows,
      ImportStatus.COMPLETED,
      summary.errors,
      summary,
      this.importedBy,
      this.importedAt,
      new Date(),
    );
  }

  /**
   * Marks the import as failed
   */
  fail(errors: ImportError[]): ResourceImportEntity {
    const summary: ImportSummary = {
      totalRows: this.totalRows,
      successfulRows: this.successfulRows,
      failedRows: this.totalRows - this.successfulRows,
      errors,
      warnings: [],
      duration: Date.now() - this.importedAt.getTime(),
    };

    return new ResourceImportEntity(
      this.id,
      this.filename,
      this.originalFilename,
      this.totalRows,
      this.successfulRows,
      this.totalRows - this.successfulRows,
      ImportStatus.FAILED,
      errors,
      summary,
      this.importedBy,
      this.importedAt,
      new Date(),
    );
  }

  /**
   * Cancels the import
   */
  cancel(): ResourceImportEntity {
    return new ResourceImportEntity(
      this.id,
      this.filename,
      this.originalFilename,
      this.totalRows,
      this.successfulRows,
      this.failedRows,
      ImportStatus.CANCELLED,
      this.errors,
      this.summary,
      this.importedBy,
      this.importedAt,
      new Date(),
    );
  }

  /**
   * Checks if import is still in progress
   */
  isInProgress(): boolean {
    return this.status === ImportStatus.PROCESSING;
  }

  /**
   * Checks if import completed successfully
   */
  isCompleted(): boolean {
    return this.status === ImportStatus.COMPLETED;
  }

  /**
   * Checks if import failed
   */
  isFailed(): boolean {
    return this.status === ImportStatus.FAILED;
  }

  /**
   * Gets success rate as percentage
   */
  getSuccessRate(): number {
    if (this.totalRows === 0) return 0;
    return (this.successfulRows / this.totalRows) * 100;
  }
}
