/**
 * HITO 6 - RF-02: ResourceCategory Entity
 * Junction entity for multiple categories per resource
 */
export class ResourceCategoryEntity {
  constructor(
    public readonly id: string,
    public readonly resourceId: string,
    public readonly categoryId: string,
    public readonly assignedAt: Date,
    public readonly assignedBy: string,
  ) {}

  /**
   * Creates a new resource-category association
   */
  static create(
    resourceId: string,
    categoryId: string,
    assignedBy: string,
  ): ResourceCategoryEntity {
    return new ResourceCategoryEntity(
      '', // ID will be generated by repository
      resourceId,
      categoryId,
      new Date(),
      assignedBy,
    );
  }

  /**
   * Validates the association
   */
  static isValid(resourceId: string, categoryId: string): boolean {
    return resourceId.trim().length > 0 && categoryId.trim().length > 0;
  }
}
